"""remove default_model_provider column

Revision ID: b6ec7a256e4b
Revises: f1b8131d068c
Create Date: 2026-01-13 11:24:58.703679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6ec7a256e4b'
down_revision: Union[str, Sequence[str], None] = 'f1b8131d068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'default_model_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('default_model_provider', postgresql.ENUM('OPENAI', 'OPENROUTER', 'ANTHROPIC', 'GOOGLE', name='modelprovider'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
